version: "3.7"
services:
    db:
        container_name: cadastro_postgres
        image: postgres:latest
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=1234
            - POSTGRES_USER=cadastro
            - POSTGRES_DB=cadastro
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
    api:
        container_name: cadastro_api
        image: guilhermerebelo/cadastro:latest
        ports:
            - 8080:8080
        depends_on:
            - db

    front:
        container_name: cadastro_front
        image: guilhermerebelo/cadastro-front:latest
        ports:
            - 9000:80
        depends_on:
            - api

volumes:
    db: {}
